export const ROUTE_PATHS = {
  landing: '/',
  login: '/login',
  signUp: '/signup',
  verifyEmail: '/verify-email',
  onboardingBaseCurrency: '/onboarding/base-currency',
  onboardingLocalCurrencies: '/onboarding/local-currencies',
  onboardingBudget: '/onboarding/budget',
  onboardingTimezone: '/onboarding/timezone',
  onboardingProfile: '/onboarding/profile',
  home: '/home',
  expenseCreate: '/home',
  expenses: '/home/expenses',
  pots: '/home/pots',
  report: '/report',
  reportMemos: '/report/memos',
  calculator: '/calculator',
  offlineCalculator: '/offline',
  ocr: '/ocr',
  settings: '/settings',
} as const
