export const ROUTE_PATHS = {
  landing: '/',
  login: '/login',
  signUp: '/signup',
  terms: '/signup/terms',
  verifyEmail: '/verify-email',
  onboardingBaseCurrency: '/onboarding/base-currency',
  onboardingLocalCurrencies: '/onboarding/local-currencies',
  onboardingBudget: '/onboarding/budget',
  home: '/home',
  expenseCreate: '/expenses/new',
  expenses: '/expenses',
  expenseDetail: '/expenses/:expenseId',
  pots: '/pots',
  report: '/report',
  calculator: '/calculator',
  ocr: '/ocr',
  settings: '/settings',
} as const
